### ISSUE TITLE
Someting Wrong on Table Prefix

### ISSUE THREAD

**Issue by Cm-8** [vishnus/osticket-autoassign#2]
Your plugin adds some interesting features in osTicket, but after installation I got this error from osticket:
The last version of osticket add a custom prefix to osticket database tables.

```
[SELECT ost_staff.staff_id FROM ost_staff LEFT JOIN ost_ticket ON (ost_ticket.staff_id = ost_staff.staff_id AND status_id = 1) LEFT JOIN ost_role ON (ost_role.id = ost_staff.role_id)  WHERE onvacation = 0 AND isactive = 1 AND lastlogin >= DATE_SUB(NOW(), INTERVAL 1 HOUR)  AND ost_role.permissions like '%ticket.autoassign%' AND ost_staff.dept_id = 6  GROUP BY ost_staff.staff_id HAVING COUNT(ost_ticket.ticket_id) <= 150 ORDER BY RAND() LIMIT 1]

Table 'Sqlxxxxxx_5.ost_staff' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #1146', '[SELECT ost_sta...')<br />
#1 (root)/include/plugins/autoassign/autoassign.php(62): db_query('SELECT ost_staf...')<br />
#2 (root)/include/class.signal.php(98): AutoAssignTicket->doAutoAssign(Object(Ticket), NULL)<br />
#3 (root)/include/class.ticket.php(4505): Signal::send('ticket.created', Object(Ticket))<br />
#4 (root)/include/class.mailfetch.php(898): Ticket::create(Array, Array, 'Email')<br />
#5 (root)/include/class.mailfetch.php(947): MailFetcher->createTicket(1)<br />
#6 (root)/include/class.mailfetch.php(1027): MailFetcher->fetchEmails()<br />
#7 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#8 (root)/scp/autocron.php(61): Cron::MailFetcher()<br />
#9 {main}

```

**Comment by Cm-8** [comment]
@vishnus

**Comment by vishnus** [comment]
hey, yes custom table prefix I will update soon. Whats the version of osticket you're using? This has not been tested in versions above 1.10.

**Comment by Cm-8** [comment]
Hi @vishnus,
I'm using 1.14
